name = "blueprint-debug"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["BlueprintDebug"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"


[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
path = "/home/jcreed/pgit/doc-gen4"

[[lean_lib]]
name = "BlueprintDebug"
